### ISSUE TITLE
The broker example code can't executed successfully using master branch.

### ISSUE THREAD

**Issue by zhonhel** [Yakifo/amqtt#118]
I cloned the master branch code, and cd to the code dir.
Then I executed the following code which copyed from https://amqtt.readthedocs.io/en/latest/references/broker.html and putted them into `simple_broker.py`
```
import logging
import asyncio
import os
from amqtt.broker import Broker


async def broker_coro():
    broker = Broker()
    await broker.start()


if __name__ == '__main__':
    formatter = "[%(asctime)s] :: %(levelname)s :: %(name)s :: %(message)s"
    logging.basicConfig(level=logging.INFO, format=formatter)
    asyncio.get_event_loop().run_until_complete(broker_coro())
    asyncio.get_event_loop().run_forever()
```

Then I got the following error:
```
(mqtt-server) wrp@ecs-2:~/amqtt$ python simple_broker.py 
Traceback (most recent call last):
  File "/home/wrp/amqtt/amqtt/broker.py", line 201, in _build_listeners_config
    listeners_config = broker_config["listeners"]
KeyError: 'listeners'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wrp/amqtt/simple_broker.py", line 15, in <module>
    asyncio.get_event_loop().run_until_complete(broker_coro())
  File "/home/wrp/Python-3.9.13_install/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/wrp/amqtt/simple_broker.py", line 8, in broker_coro
    broker = Broker()
  File "/home/wrp/amqtt/amqtt/broker.py", line 173, in __init__
    self._build_listeners_config(self.config)
  File "/home/wrp/amqtt/amqtt/broker.py", line 208, in _build_listeners_config
    raise BrokerException("Listener config not found invalid: %s" % ke)
amqtt.broker.BrokerException: Listener config not found invalid: 'listeners'
(mqtt-server) wrp@ecs-2:~/amqtt$ 

```

**Comment by not-f-elsner** [comment]
Mh, I'm not sure if we should include a default `listeners` config in the broker, or if we should adapt the examples to provide such config

**Comment by ajmirsky** [comment]
The [default broker config](https://github.com/Yakifo/amqtt/blob/rc/amqtt/scripts/default_broker.yaml) (which is used by both the `amqtt` script and the `Broker()` class) now includes a default listener.
