### ISSUE TITLE
A failing plugin kills the broker 

### ISSUE THREAD

**Issue by volkerjaenisch** [Yakifo/amqtt#51]
Dear @all!

The exception handling of a failed import kills the broker by backstabbing:

```
    def _load_plugin(self, ep: pkg_resources.EntryPoint):
        try:
            self.logger.debug(" Loading plugin %s" % ep)
            plugin = ep.load(require=True)
            self.logger.debug(" Initializing plugin %s" % ep)
            plugin_context = copy.copy(self.app_context)
            plugin_context.logger = self.logger.getChild(ep.name)
            obj = plugin(plugin_context)
            return Plugin(ep.name, ep, obj)
        except ImportError as ie:   <- this line
            self.logger.warning("Plugin %r import failed: %s" % (ep, ie))
        except pkg_resources.UnknownExtra as ue:
            self.logger.warning("Plugin %r dependencies resolution failed: %s" % (ep, ue))
```

Plugins are imported via pkg_resources. If the plugin fails to load (due to an internal error) an ImportError is raised via pkg_resources. This leads to a return value of None to the calling routine, leading to the happy but wrong message:

```

[2021-03-31 00:32:08,049] :: WARNING - Plugin EntryPoint.parse('amqtt_db = amqtt_db.plugin:DBPlugin') import failed: 'amqtt_db'
[2021-03-31 00:32:08,049] :: DEBUG -  Plugin amqtt_db ready
```

and then to this stacktrace:

```
future: <Task finished coro=<Broker.stream_connected() done, defined at /home/volker/workspace/venvs/amqtt-db-Sb9e8jh5-py3.7/lib/python3.7/site-packages/hbmqtt/broker.py:335> exception=AttributeError("'NoneType' object has no attribute 'name'")>
Traceback (most recent call last):
  File "/home/volker/workspace/venvs/amqtt-db-Sb9e8jh5-py3.7/lib/python3.7/site-packages/hbmqtt/broker.py", line 336, in stream_connected
    await self.client_connected(listener_name, StreamReaderAdapter(reader), StreamWriterAdapter(writer))
  File "/home/volker/workspace/venvs/amqtt-db-Sb9e8jh5-py3.7/lib/python3.7/site-packages/hbmqtt/broker.py", line 386, in client_connected
    authenticated = await self.authenticate(client_session, self.listeners_config[listener_name])
  File "/home/volker/workspace/venvs/amqtt-db-Sb9e8jh5-py3.7/lib/python3.7/site-packages/hbmqtt/broker.py", line 541, in authenticate
    filter_plugins=auth_plugins)
  File "/home/volker/workspace/venvs/amqtt-db-Sb9e8jh5-py3.7/lib/python3.7/site-packages/hbmqtt/plugins/manager.py", line 206, in map_plugin_coro
    return (await self.map(self._call_coro, coro_name, *args, **kwargs))
  File "/home/volker/workspace/venvs/amqtt-db-Sb9e8jh5-py3.7/lib/python3.7/site-packages/hbmqtt/plugins/manager.py", line 168, in map
    p_list = [p.name for p in self.plugins]
  File "/home/volker/workspace/venvs/amqtt-db-Sb9e8jh5-py3.7/lib/python3.7/site-packages/hbmqtt/plugins/manager.py", line 168, in <listcomp>
    p_list = [p.name for p in self.plugins]
AttributeError: 'NoneType' object has no attribute 'name'
```
Where the None is the return value of the failed loading of the plugin.

From the perspective of a user this cannot be understood. Even as a developer you are challenged.

I propose to push the exception handling simply a level up into 

```
def _load_plugins(self, namespace):
        self.logger.debug("Loading plugins for namespace %s" % namespace)
        for ep in pkg_resources.iter_entry_points(group=namespace):
            plugin = self._load_plugin(ep)
            self._plugins.append(plugin)
            self.logger.debug(" Plugin %s ready" % ep.name)
```

Here the exceptions can be handled with more context and consistency. 

Shall I do a pullrequest or are you fixing this by yourselves?

Cheers,
Volker

**Comment by volkerjaenisch** [comment]
I have correct myself. The ImportError is not raised by pkg_resources but by my plugin. And it is the right thing to raise if the import of a plugin fails.

**Comment by FlorianLudwig** [comment]
I agree, the error handling should be improved!

It should be discussed what the expected behavior is - should a broken plugin stop the broker from starting?

Since plugins are loaded at startup I would actually prefer if we fail with a great error message instead of ignoring errors.

@volkerjaenisch what is your take on this?

@HerrMuellerluedenscheid what is your take on this?

**Comment by HerrMuellerluedenscheid** [comment]
I agree with @FlorianLudwig that the broker should not even start when there is a broken plugin being loaded. It would be different if plugins were (un-)loaded at run time.

Allowing the broker to start with a broken plugin may easily lead to very surprising behavior. E.g. let's say there a two plugins `A` and `B`. `A` is broken and a warning shows up in the logs. `B` works fine but produces a lot of logging output. In that scenario the failure of `A` might easily be overseen. That would be very surprising, wouldn't it?

**Comment by volkerjaenisch** [comment]
Ah and not to forget. We should specify an Exception that a plugin has to raise to inform the broker that it is not capable of running.
My plugin e.g. throws an ImportError since this is the Exception the plugin loader looks for. But there may be better solutions.
