### ISSUE TITLE
0.10.0 trows exception on connect

### ISSUE THREAD

**Issue by hernrup-modelon** [Yakifo/amqtt#83]
Version: 1.10.0
Python: 3.8.10

Output broker:
```
▶ amqtt                                      
[2021-11-26 08:50:05,493] :: INFO - Finished processing state new exit callbacks.
[2021-11-26 08:50:05,493] :: INFO - Finished processing state starting enter callbacks.
[2021-11-26 08:50:05,493] :: INFO - ### 'on_broker_pre_start' EVENT FIRED ###
[2021-11-26 08:50:05,494] :: INFO - Listener 'default' bind to 0.0.0.0:1883 (max_connections=-1)
[2021-11-26 08:50:05,494] :: INFO - Finished processing state starting exit callbacks.
[2021-11-26 08:50:05,494] :: INFO - Finished processing state started enter callbacks.
[2021-11-26 08:50:05,494] :: INFO - ### 'on_broker_post_start' EVENT FIRED ###
[2021-11-26 08:50:09,831] :: INFO - Listener 'default': 1 connections acquired
[2021-11-26 08:50:09,831] :: INFO - Connection from 127.0.0.1:59932 on listener 'default'
[2021-11-26 08:50:09,832] :: INFO - ### 'on_mqtt_packet_received' EVENT FIRED ###
[2021-11-26 08:50:09,832] :: ERROR - Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Broker.stream_connected() done, defined at /src/HBMQTT_Paho_MySQL_MongoDB/venv/lib/python3.8/site-packages/amqtt/broker.py:394> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/src/HBMQTT_Paho_MySQL_MongoDB/venv/lib/python3.8/site-packages/amqtt/broker.py", line 395, in stream_connected
    await self.client_connected(
  File "/src/HBMQTT_Paho_MySQL_MongoDB/venv/lib/python3.8/site-packages/amqtt/broker.py", line 461, in client_connected
    authenticated = await self.authenticate(
  File "/src/HBMQTT_Paho_MySQL_MongoDB/venv/lib/python3.8/site-packages/amqtt/broker.py", line 688, in authenticate
    returns = await self.plugins_manager.map_plugin_coro(
  File "/src/HBMQTT_Paho_MySQL_MongoDB/venv/lib/python3.8/site-packages/amqtt/plugins/manager.py", line 212, in map_plugin_coro
    return await self.map(self._call_coro, coro_name, *args, **kwargs)
  File "/src/HBMQTT_Paho_MySQL_MongoDB/venv/lib/python3.8/site-packages/amqtt/plugins/manager.py", line 188, in map
    ret_list = await asyncio.gather(*tasks, loop=self._loop)
  File "/src/HBMQTT_Paho_MySQL_MongoDB/venv/lib/python3.8/site-packages/amqtt/plugins/manager.py", line 201, in _call_coro
    coro = getattr(plugin.object, coro_name)(*args, **kwargs)
TypeError: 'NoneType' object is not callable
```

Output Client:
```
▶ amqtt_sub --url mqtt://localhost -t /test/#
```

Environment:
```
▶ pip list
Package       Version
------------- -------
amqtt         0.10.0 
docopt        0.6.2  
paho-mqtt     1.6.1  
passlib       1.7.4  
pip           20.0.2 
pkg-resources 0.0.0  
PyYAML        5.4.1  
setuptools    44.0.0 
six           1.16.0 
transitions   0.8.10 
websockets    9.1  
```

**Comment by HerrMuellerluedenscheid** [comment]
Thanks for opening the issue. I can reproduce the problem.
